services:
  redis-a:
    image: redis
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./node-a/cluster.conf:/etc/redis/redis.conf
  redis-b:
    image: redis
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./node-b/cluster.conf:/etc/redis/redis.conf
  redis-c:
    image: redis
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./node-c/cluster.conf:/etc/redis/redis.conf
  controller:
    image: redis
    command: >
      bash -c "
      redis-cli --cluster create --cluster-yes --cluster-replicas 0 redis-a:6379 redis-b:6379 redis-c:6379 &&
      source_id=$$(redis-cli -h redis-b cluster myid) &&
      target_id=$$(redis-cli -h redis-c cluster myid) &&
      redis-cli -h redis-c cluster setslot 6000 importing $$source_id &&
      redis-cli -h redis-b cluster setslot 6000 migrating $$target_id &&
      redis-cli -h redis-c cluster setslot 6000 node $$target_id &&
      redis-cli -h redis-b cluster setslot 6000 node $$target_id &&
      redis-cli -h redis-a cluster setslot 6000 node $$target_id &&
      touch /tmp/cluster-ready;
      while true; do
        redis-cli -h redis-a cluster info | grep cluster_state:fail;
        sleep 1;
      done"
    healthcheck:
      test: "test -f /tmp/cluster-ready && redis-cli -h redis-a cluster info | grep cluster_state:ok"
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      - redis-a
      - redis-b
      - redis-c
  tests:
    image: ruby:${RUBY_VERSION:-latest}
    volumes:
      - ../../:/code
    command: bash -c "cd /code && bundle install && bundle exec sus integration/cluster/test"
    environment:
      - COVERAGE=${COVERAGE}
    depends_on:
      controller:
        condition: service_healthy
