# Copyright, 2018, by Samuel G. D. Williams. <http://www.codeotaku.com>
# Copyright, 2018, by Huba Nagy.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# DO NOT manually edit this file it was generated based on https://raw.githubusercontent.com/antirez/redis-doc/master/commands.json.

module Async
	module Redis
		module Methods
			module AutoGenerated
				module Streams
					def xinfo(*arguments)
						return call('XINFO', arguments)
					end

					def xadd(*arguments)
						return call('XADD', arguments)
					end

					def xtrim(*arguments)
						return call('XTRIM', arguments)
					end

					def xdel(*arguments)
						return call('XDEL', arguments)
					end

					def xrange(*arguments)
						return call('XRANGE', arguments)
					end

					def xrevrange(*arguments)
						return call('XREVRANGE', arguments)
					end

					def xlen(*arguments)
						return call('XLEN', arguments)
					end

					def xread(*arguments)
						return call('XREAD', arguments)
					end

					def xgroup(*arguments)
						return call('XGROUP', arguments)
					end

					def xreadgroup(*arguments)
						return call('XREADGROUP', arguments)
					end

					def xack(*arguments)
						return call('XACK', arguments)
					end

					def xclaim(*arguments)
						return call('XCLAIM', arguments)
					end

					def xpending(*arguments)
						return call('XPENDING', arguments)
					end

				end
			end
		end
	end
end
