name: Test Cluster

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
        
        experimental: [false]
    
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "4.0"
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 10
      env:
        RUBY_VERSION: ${{matrix.ruby}}
      run: bundle exec bake test:integration name=cluster build=false
