name: Test Coverage

on: [push, pull_request]

permissions:
  contents: read

env:
  COVERAGE: PartialSummary

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - ruby
    
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 5
      run: bundle exec bake test
    
    - uses: actions/upload-artifact@v7
      with:
        include-hidden-files: true
        if-no-files-found: error
        name: coverage-${{matrix.os}}-${{matrix.ruby}}
        path: .covered.db
  
  test-sentinel:
    name: ${{matrix.ruby}} on ${{matrix.os}} (Sentinel)
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - "3.4"
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Run tests
      timeout-minutes: 10
      working-directory: integration/sentinel
      env:
        RUBY_VERSION: ${{matrix.ruby}}
      run: docker compose up --exit-code-from tests
    
    - uses: actions/upload-artifact@v7
      with:
        include-hidden-files: true
        if-no-files-found: error
        name: coverage-${{matrix.os}}-${{matrix.ruby}}-sentinel
        path: .covered.db
  
  test-cluster:
    name: ${{matrix.ruby}} on ${{matrix.os}} (Cluster)
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - "3.4"
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Run tests
      timeout-minutes: 10
      working-directory: integration/cluster
      env:
        RUBY_VERSION: ${{matrix.ruby}}
      run: docker compose up --exit-code-from tests
    
    - uses: actions/upload-artifact@v7
      with:
        include-hidden-files: true
        if-no-files-found: error
        name: coverage-${{matrix.os}}-${{matrix.ruby}}-cluster
        path: .covered.db
  
  validate:
    needs: 
      - test
      - test-sentinel
      - test-cluster
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    
    - uses: actions/download-artifact@v8
    
    - name: Validate coverage
      timeout-minutes: 5
      run: bundle exec bake covered:validate --paths */.covered.db \;
